// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using projeto.tcc.wallet.management.infra.data.Context;

namespace projeto.tcc.wallet.management.infra.data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20200608001622_CreateAsset")]
    partial class CreateAsset
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("projeto.tcc.wallet.management.domain.Aggregates.AssetAggregate.Asset", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("_name")
                        .HasColumnName("Name")
                        .HasColumnType("text");

                    b.Property<decimal>("_startPrice")
                        .HasColumnName("StartPrice")
                        .HasColumnType("numeric");

                    b.Property<string>("_symbol")
                        .HasColumnName("Symbol")
                        .HasColumnType("text");

                    b.Property<Guid>("_userId")
                        .HasColumnName("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("Asset");
                });

            modelBuilder.Entity("projeto.tcc.wallet.management.domain.Aggregates.BalanceAggregate.UserBalance", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("_totalPatrimony")
                        .HasColumnName("TotalProperty")
                        .HasColumnType("numeric");

                    b.Property<decimal>("_transientBalance")
                        .HasColumnName("TrasientBalance")
                        .HasColumnType("numeric");

                    b.Property<Guid>("_userId")
                        .HasColumnName("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("Balance");
                });
#pragma warning restore 612, 618
        }
    }
}
